### ISSUE TITLE
Wooden buckets cannot be used to fill an AgriCraft water pad

### ISSUE THREAD

**Issue by Haggle1996** [BuiltBrokenModding/SingleBlockMods#11]
see Haggle1996/RevolutionPack#432

**Comment by DarkGuardsman** [comment]
Wil see what is up sometime this weekend, also might have to find a video on the mod as I've never used it.

**Comment by DarkGuardsman** [comment]
@Haggle1996 I'm going to implement a quick fix but this is a bug on Argicraft's end. They do not support IFluidContainers in their code, and forge doesn't allow for NBT items to be registered as buckets.

**Comment by Haggle1996** [comment]
Thank you. I'm sure my players will be happy to see the fix.

**Comment by DarkGuardsman** [comment]
Issue should be solved in the next release, just have to wait on @dmodoomsirius to fix the build scripts.

**Comment by dmodoomsirius** [comment]
@Haggle1996 update is now on curse :) enjoy
