### ISSUE TITLE
[1.12 Crash] Forge 2389

### ISSUE THREAD

**Issue by MokahTGS** [BuiltBrokenModding/SingleBlockMods#13]
Getting a crash with Forge 2389

https://pastebin.com/VZrf71ep

**Comment by DarkGuardsman** [comment]
Wrong repo, you wanted this one
https://github.com/BuiltBrokenModding/SBM-woodenBucket

As well you forgot to install the dep VoltzEngine Fluid module
https://minecraft.curseforge.com/projects/ve-fluidhandling/files
