### ISSUE TITLE
Add HarvestCraft Support

### ISSUE THREAD

**Issue by InkDragon** [BuiltBrokenModding/SingleBlockMods#2]
would it be possible to add compatibility between wooden buckets and Harvest Craft to convert milk/water(in wooden buckets) to fresh milk/water

**Comment by DarkGuardsman** [comment]
It should be possible but I may not get to adding support to it for a while.

**Comment by GreenCafe** [comment]
It's possible but it depends on the developers mood and if s/he has the time

**Comment by DarkGuardsman** [comment]
Not too worried about the developer of the mod. As it can most likely ore dict the recipes for conversion.

**Comment by GreenCafe** [comment]
That's true

**Comment by InkDragon** [comment]
thank you and no rush <3

**Comment by DarkGuardsman** [comment]
Ok basic support was added. I'll need to test it more before I make a release to curse. Especially since it looks like the bucket is consumed in each recipe.
