### ISSUE TITLE
Petal Apothecary destroys Buckets

### ISSUE THREAD

**Issue by SkullyGamingMC** [BuiltBrokenModding/SingleBlockMods#5]
Whenever I right-click on Botania's Petal Apothecary with a Wooden Bucket, it destroys the Bucket after filling the Apothecary with Water. Since all other containers work fine with the Apothecary, I assume the issue is on your side.

**Comment by DarkGuardsman** [comment]
Are you using the latest version?

**Comment by DarkGuardsman** [comment]
Confirmed the bug, should have it fixed soon

**Comment by DarkGuardsman** [comment]
http://minecraft.curseforge.com/projects/sbm-wooden-buckets/files/2265748
