### ISSUE TITLE
[sbm Wooden buckets] Buckets do not produce milk

### ISSUE THREAD

**Issue by Haggle1996** [BuiltBrokenModding/SingleBlockMods#8]
With only Forge 1448 and SBM Wooden Buckets, right clicking on cows makes the bucket disappear. Clicking in your task bar where the bucket was will cause the bucket to appear in your hand with no milk inside. Tried all buckets (oak, birch, etc.) Cannot get milk. Cannot spill milk in an effort to cry over it.

Present in 3b6 as well as 3b2015.... versions.

**Comment by dmodoomsirius** [comment]
I will look into this shortly.

**Comment by DarkGuardsman** [comment]
Could be a bug generated when I changed how buckets fill to fix issues with botania. I'll try to fix it this week but its finals weeks. So it may end up waiting until the back end of the week.

**Comment by Haggle1996** [comment]
Haggle1996/RevolutionPack#137

**Comment by Haggle1996** [comment]
*bump* :D

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/SingleBlockMods/commit/fc08dd7972915aa2b8eaf1884717e4a8f0647001

Fixed, but I might not get you a new build until after the holidays. Sorry for the wait...

**Comment by Haggle1996** [comment]
No worries. Holidays are meant to be enjoyed.

**Comment by Haggle1996** [comment]
Any chance of getting that fix? Also can't use wooden buckets with creosote. :D

**Comment by dmodoomsirius** [comment]
I will attempt to upload a new build tonight.

**Comment by Haggle1996** [comment]
Thank you. Much appreciated.

**Comment by DarkGuardsman** [comment]
My apologies I thought I already uploaded a file a few weeks ago. If dmod does not get the file uploaded I will get it after this class.

**Comment by dmodoomsirius** [comment]
Compiling right now.

**Comment by dmodoomsirius** [comment]
uploaded to curse waiting for them to approve it. Will close when approved.

**Comment by Haggle1996** [comment]
Thank you very much!
